// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQhHloHS5wMfCX4yUKxUNlUUP4CCi95wE',
    appId: '1:572024193899:web:81a4ed6522e24f38e4022e',
    messagingSenderId: '572024193899',
    projectId: 'smart-crop-detection',
    authDomain: 'smart-crop-detection.firebaseapp.com',
    storageBucket: 'smart-crop-detection.firebasestorage.app',
    measurementId: 'G-DB033G38YE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr3mcw89fH9rCaoovxx49NmCTMOkEAlh0',
    appId: '1:572024193899:android:8b91722d7670ef0fe4022e',
    messagingSenderId: '572024193899',
    projectId: 'smart-crop-detection',
    storageBucket: 'smart-crop-detection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCWqttFERvwXBlVfiV_feMklonMdiKG3Q',
    appId: '1:572024193899:ios:029311746263ca3ae4022e',
    messagingSenderId: '572024193899',
    projectId: 'smart-crop-detection',
    storageBucket: 'smart-crop-detection.firebasestorage.app',
    iosBundleId: 'com.example.smartCropDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCWqttFERvwXBlVfiV_feMklonMdiKG3Q',
    appId: '1:572024193899:ios:029311746263ca3ae4022e',
    messagingSenderId: '572024193899',
    projectId: 'smart-crop-detection',
    storageBucket: 'smart-crop-detection.firebasestorage.app',
    iosBundleId: 'com.example.smartCropDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQhHloHS5wMfCX4yUKxUNlUUP4CCi95wE',
    appId: '1:572024193899:web:934e7bc7e7f86a3fe4022e',
    messagingSenderId: '572024193899',
    projectId: 'smart-crop-detection',
    authDomain: 'smart-crop-detection.firebaseapp.com',
    storageBucket: 'smart-crop-detection.firebasestorage.app',
    measurementId: 'G-PXDFPW2GB7',
  );
}
